### ISSUE TITLE
GD32 Chips

### ISSUE THREAD

**Issue by Alexandre-Mainardi** [alex-makarov/robaka-ros#1]
Hi Alex, 

I notice you are using a GD32F103 chip based main board, did you have any problems to build or upload the original Niklas code? Im trying to upload the code using STLink v2, but my board doesn't enter on DFU mode using the power wires.

Thanks for sharing the project!

**Comment by sebastienvg** [comment]
don't use the power from ST-LINK only GND SWDIO & SWCLK then power the board from the battery pack and then short the power button of the hoverboard mainboard (or keep the button press), that should bring you to "jolly good!"
