### ISSUE TITLE
rosdep install robaka error

### ISSUE THREAD

**Issue by emo8899** [alex-makarov/robaka-ros#15]
![1713257904182](https://github.com/alex-makarov/robaka-ros/assets/108335283/f66cd310-b852-4fe6-a73a-c219f1282cbf)
hi alex
 my os version:18.04, but i cant run rosdep install robaka. please help check this. thanks~

**Comment by emo8899** [comment]
fixed

**Comment by sebastienvg** [comment]
how was this fixed? ```seb@tangerine-rover:~/catkin_ws$ rosdep install robako

ERROR: Rosdep cannot find all required resources to answer your query
Missing resource robako
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/opt/ros/melodic/share```
