### ISSUE TITLE
thanks!

### ISSUE THREAD

**Issue by btsimonh** [alex-makarov/robaka-ros#7]
Hi Alex,
thanks for mentioning and using our repo.
I created it specifically for this kind of purpose, but have had so little time over the last year or so to give it attention.
However, yesterday I obtained a 22v vacuum cleaner, so at least one of my hoverboards will now have purpose - to pick up the doghair everywhere....
br,
btsimonh

**Comment by alex-makarov** [comment]
Hey @btsimonh , 

sorry for the late reply. You've done absolutely amazing job, enabling construction of pretty complex platforms on a cheap but powerful chassis. Definitely deserves more recognition in the robotics community! Kudos! 

Alex
