### ISSUE TITLE
Which Bipropellant firmware mode used?

### ISSUE THREAD

**Issue by Andyzug** [alex-makarov/robaka-ros#8]
Hi!
Tell me please which Bipropellant firmware mode you used in this project?
There are 9 modes that can be build, like:

;default_envs = genericSTM32F103RC
;default_envs = hoverboard
;default_envs = hoverboard_6word
;default_envs = control_softwareserial
;default_envs = control_usart2
;default_envs = control_usart3
;default_envs = control_usart3_ADC
;default_envs = control_ADC
;default_envs = control_PPM

Thank you.

**Comment by alex-makarov** [comment]
Hey @Andyzug ,  I'm using control_usart2.

Alex
