### ISSUE TITLE
Script for gpio

### ISSUE THREAD

**Issue by darld** [alex-makarov/robaka-ros#9]
@alex-makarov Which script you used for send outputs to gpio?

**Comment by alex-makarov** [comment]
hey @darld ,

It depends on what gpio you mean. 

I'm using [hoverboard-driver](https://github.com/alex-makarov/hoverboard-driver) for the motors via UART pins. IMU and LCD display are connected via I2C pins on GPIO, you can find respective launch files in the repository.

**Comment by darld** [comment]
@alex-makarov May I know how many repo used for the roboka V2? It is only 
https://github.com/alex-makarov/robaka-ros
https://github.com/alex-makarov/hoverboard-driver

I planning to build a prototype for remote control mobile robot over 4G / 5G connection, do you have any advise? 
Your reply is highly appreciated.
